name: Deploy Voice to Text Figma Plugin

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Get Secret Manager secrets
        uses: google-github-actions/get-secretmanager-secrets@v2.2.3
        with:
          secrets: |
            RAILWAY_API_TOKEN:projects/YOUR_PROJECT_ID/secrets/RAILWAY_API_TOKEN:latest
            CUSTOM_SECRET:projects/YOUR_PROJECT_ID/secrets/CUSTOM_SECRET:latest

      - name: Build
        run: npm run build

      - name: Deploy to Railway
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://backboard.railway.app/graphql \
            --data '{"query":"mutation { deploymentCreate(input: { projectId: \"YOUR_PROJECT_ID\" }) { deployment { id status } } }"}'
